### PR TITLE
Ability to connect to remote Selenium server

### PR DESCRIPTION
**Pull request by tfga**
Fixes issue #234.

The user still has to specify `<serverHostname>` for this to work, e.g.:

``` xml
<remoteWebDriverUrl>http://seleniumServer:4444/wd/hub</remoteWebDriverUrl>
<serverHostname>localIpOrHostname</serverHostname>
```

### CODE REVIEW

**Comment by vmassol** [comment]
It would really be nice to support RemoteWebDriver in the jasmine maven plugin, as this would allow using docker to start the `selenium/standalone-chrome` docker image for chrome and have jasmin tests execute with it. This will avoid having to install the chrome headless binaries locally for example.

I find it nicer than using https://github.com/Ardesco/driver-binary-downloader-maven-plugin to get the `webdriver.chrome.driver`  property in maven and pass it to the jasmine plugin.

This PR is from 2014 now. Starting to be quite old. Has any progress been made to support RemoteWebDriver?

I see in the sources the mention of RemoteWebDriver at https://github.com/searls/jasmine-maven-plugin/blob/ce365e7c908666e883908dd8e271f92c39d1be49/src/main/java/com/github/searls/jasmine/mojo/AbstractJasmineMojo.java#L290 but I couldn't find any example of using it.

Thanks for a great plugin!

**Comment by vmassol** [comment]
> I find it nicer than using https://github.com/Ardesco/driver-binary-downloader-maven-plugin to get the webdriver.chrome.driver property in maven and pass it to the jasmine plugin.

Actually I see that the code is using WebDriverManager so that's a better solution and it doesn't need https://github.com/Ardesco/driver-binary-downloader-maven-plugin since it should do the binary download by itself.

I guess I need to try to see if RemoteWebDriver is supported but I see no reason why it couldn't be instantiated by WebDriverManager actually. So I guess it should work.

**Comment by vmassol** [comment]
Actually WebDriverManager will download the driver but not the browser. So the docker solution seems to be the only solution to not have to install anything locally (except doker ofc ;))

**Comment by searls** [comment]
Hi @vmassol. I haven't worked on this lib for years personally, but I hope @klieber might be available to comment on what level of maintenance he considers the library to be in and what he'd need to see in a feature request at this point

**Comment by klieber** [comment]
Hi @vmassol @searls.  Honestly I haven't really had time to work on this plugin in a long time and I haven't personally used it for any projects in about 6 - 7 years.  I still do development in both javascript and java but there are just better ways to unit test javascript these days and all of it revolves around node / npm.  Personally, when I have a maven based project now that also includes javascript I use the [frontend-maven-plugin](https://github.com/eirslett/frontend-maven-plugin).  That setup allows you to use node / npm for your javascript related stuff while still keeping the build as simple as running `mvn install`.

All that said, I think it's long overdo that I put a message on the README of this project stating that it is no longer being maintained and I will include my suggestions on alternative solutions.

**Comment by vmassol** [comment]
hey, thanks to both of you @searls & @klieber for your replies.

> I still do development in both javascript and java but there are just better ways to unit test javascript these days and all of it revolves around node / npm. Personally, when I have a maven based project now that also includes javascript I use the frontend-maven-plugin. That setup allows you to use node / npm for your javascript related stuff while still keeping the build as simple as running mvn install.

I'm curious about this. We have some javascript to test and I fear that testing it on the server side (with node) would not ensure it'll work fine at runtime since it executes on the client side in our case (in FF or Chrome browsers). Also we don't use any Bower, Grunt, Gulp, Jspm, Karma, or Webpack as mentioned on https://github.com/eirslett/frontend-maven-plugin, so not sure it's the right solution in our case. Now I'm not the one who wrote this javascript and javascript is not my language of expertise (I'm a java guy) so maybe I'm just plain wrong. I'm just helping on the build side of XWiki here, trying to ensure that we can test our javascript through Maven and ideally that it doesn't require installing anything on the machine where it executes (except docker).

I'll check https://github.com/eirslett/frontend-maven-plugin a bit more to see if I don't miss something obvious. Feedback most welcome too ;)

Thanks guys

**Comment by klieber** [comment]
When I post a message regarding this plugin no longer being maintained I plan to include some examples of how to use the frontend-maven-plugin in its place. That plugin will install node / mom automatically so no requirement to have that pre-installed.

**Comment by vmassol** [comment]
@klieber 

>  That plugin will install node / mom automatically so no requirement to have that pre-installed.

Yes that's good but it'll still install something on the host machine! ;)

**Comment by tfga** [comment]
@vmassol
I've been using this since 2014 (had to publish my fork on the company repo under a different `groupId`). Never had any problems.

@klieber 
Before declaring the project "officially dead", maybe you could merge the PRs (this and #236) and publish a final release? 🤔

**Comment by klieber** [comment]
I will take a look at merging those but can't promise anything. I am planning on getting a stable 3.0 release with `ChromeDriver` out there before closing the door on it.

**Pull request closed without merging**
