### PR TITLE
Upgrade Selenium 2.53.1->3.0.1, Java 1.6->1.8, phantomjsdriver 1.2.1-1.3.0

### PR DESCRIPTION
**Pull request by tntim96**
This is an initial trial of some upgrades to see if the build passes on Travis CI.

Note the `PhantomJsLocator` has been removed as it wasn't working and I'm not sure of the need for it. Perhaps it can be removed or if needed, I can dig into why it was breaking.

### CODE REVIEW

**Comment by tntim96** [comment]
Yay finally got this working. Are you able to look at the {{PhantomJsLocator}} removal?

**Comment by klieber** [comment]
PhantomJsLocator is a vital piece of functionality so I'm not sure why you would remove it. Also, I don't have plan to drop support for Java 6 at this time. I probably will at some point in the next 6 months or so but that will be a major change that could prevent some stuck on Java 6 from upgrading so I'm not in any rush.

**Comment by tntim96** [comment]
> PhantomJsLocator is a vital piece of functionality so I'm not sure why you would remove it

It broke my build locally. My build (and Travis) passes without it. I'll look into the cause and add it back in.

>  I don't have plan to drop support for Java 6 at this time

Sure, but why not maintain two branches so people can use the latest Selenium? I'm happy to help.

**Comment by spyhunter99** [comment]
does this by chance bring this project to the point where ES6 code can be tested? Ran into some issues with the last release the other day with a very old version of jquery failing to load due to the keyword "in" which i think is an ES6 construct

**Comment by klieber** [comment]
This issue is no longer relevant.  The next release will have the latest version of Selenium and require Java 8.  Also, support for PhantomJS has been dropped in favor of headless Chrome.

**Pull request closed without merging**
