### PR TITLE
Adds the Ability To Define Custom Reporters

### PR DESCRIPTION
**Pull request by samjonester**
* Adds the ability to define Standard Out reporters and File System reporters through plugin configuration.
* Adds documentation for defining custom reporters.
* Adds example project with cucumber test for defining custom reporters.
* Refactors responsibilities out of larger classes.

### CODE REVIEW

**Comment by dylanb** [comment]
@searls @klieber any feedback on this PR?

**Comment by klieber** [comment]
@dylanb, thanks for the pull request! It looks good to me. I'll try to get it in a release soon.

**Comment by dylanb** [comment]
Thanks to @samjonester

**Comment by klieber** [comment]
Yes, sorry about that. Thanks to @samjonester for the pull request. Thanks @dylanb for reminding me to look at it. :)

**Comment by dylanb** [comment]
@klieber When do you think this change will be published?

**Comment by klieber** [comment]
Should be out there now: http://repo1.maven.org/maven2/com/github/searls/jasmine-maven-plugin/2.2/

**Pull request merged**
