### PR TITLE
try to find a free port if default already in use

### PR DESCRIPTION
**Pull request by just-boris**
Now if specified port already is being used, plugin will throw an exception. It would be nice  to be able try another port without extra bothering. [Karma test runner](http://karma-runner.github.io) already have [this feature](https://github.com/karma-runner/karma/blob/9690d4ecafff914c3640d0e34027065b6897fe5c/lib/server.js#L151).

I often use your project when I have to test front end within java applications, and I wish to have this feature here as well. It will try to connect the default port, and if it is used, then try next port, and throw the error only if all of next 10 ports already busy.

### CODE REVIEW

**Comment by mprins** [comment]
You might want to use [InetSocketAddress](https://docs.oracle.com/javase/7/docs/api/java/net/InetSocketAddress.html) with a portnumber of 0 to find a free ephemeral port.

eg.
```java
int newPort = new java.net.InetSocketAddress(0).getPort();
```

**Comment by just-boris** [comment]
Yes, I saw that behaviour.
But the main feature, which my logic gives, is a predictable used port range. Sometimes, (with a firewall, for example), you cannot connect to random port, but can setup trusted range (`8234-8244` here by default).

Is there an another way to get free port from some given range?

**Comment by mprins** [comment]
> Is there an another way to get free port from some given range?
AFAIK no.

**Comment by klieber** [comment]
This should be resolved in `3.0-beta-01`.  I decided to go with the simpler and more performant approach of just allowing the system to choose a random port if `8234` is not available.  Seems to work nicely with the changes in #352 which automatically opens the browser and navigates to the spec runner for you.

**Pull request closed without merging**
